---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
  name: {{basename .Name| hyphenize}}-{{hyphenize .Version.Version}}-rp
spec:
  application: {{.Name | hyphenize}}-{{hyphenize .Version.Version}}
  tenantPipeline:
    serviceAccountName: release-registry-{{.Name | hyphenize}}-{{hyphenize .Version.Version}}
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/openshift-pipelines-konflux/hack.git
        - name: revision
          # value: {{- if or (eq .Version.Version "main") (eq .Version.Version "next")  }}  {{.Version.Version}} {{- else}} release-v{{.Version.Version}}.x {{end}}
          value: main
        - name: pathInRepo
          value: pipelines/release.yaml
    params:
      - name: released_version
        value: "{{.Version.Version}}"
      - name: ReleaseToGitHub
        value: "{{.ReleaseToGitHub}}"
