name: operator
components:
  - name: index
    dockerfile: .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
    nudges: [ ]
tekton:
  watched-sources: (".konflux/patches/***".pathChanged() || ".konflux/olm-catalog/index/***".pathChanged())
branches:
  - name: main
    versions:
      - main
