---
name: Apply konflux configurations

on:
  schedule:
     - cron: "0 4 * * *" # Daily at 04:00.
  workflow_dispatch: # Manual workflow trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  apply-project:
    if: github.repository_owner == 'openshift-pipelines' # do not run this elsewhere
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Apply configurations
      run: |
        kubectl config set-credentials konflux-sa --token "$KONFLUX_TOKEN"
        kubectl config set-cluster konflux --server=https://api.stone-prd-rh01.pg1f.p1.openshiftapps.com:6443
        kubectl config set-context konflux-sa@konflux --user=konflux-sa --namespace=tekton-ecosystem-tenant --cluster=konflux
        kubectl config use-context konflux-sa@konflux
        kubectl get pr
        kubectl apply -Rf .konflux
        #go run ./cmd/konflux-apply/ -config config/konflux/${{matrix.project}}.yaml
      env:
        KONFLUX_TOKEN: ${{ secrets.KONFLUX_SA_TOKEN }}
